### ISSUE TITLE
Gas properties setting is not working

### ISSUE THREAD

**Issue by raspopov** [Lorexe/MekaTweaker#1]
Functions setUnlocalizedName, setColorize and setColor is not working, gas name and color not changes i.e. at end only one gas has been registered: `<gas:liquiduranium>` (white color).

File 1 (creating liquid):
```
#priority 3
#loader contenttweaker
#modloaded mekanism

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
import mods.contenttweaker.Fluid;
import mods.contenttweaker.Color;

var liquidUranium = VanillaFactory.createFluid("liquiduranium", Color.fromHex("408040"));
liquidUranium.register();
```

File 2 (adding gaseous version of liquid):
```
#priority 2
#modloaded contenttweaker
#modloaded mekanism

import mods.gastweaker.GasFactory;
import mods.gastweaker.Gas;

var gasCleanUraniumSlurry = GasFactory.createFromFluid(<liquid:liquiduranium>);
gasCleanUraniumSlurry.setUnlocalizedName("cleanuranium");
gasCleanUraniumSlurry.setColorize(true);
gasCleanUraniumSlurry.setColor(0x408040);
gasCleanUraniumSlurry.register();
```

Minecraft: 1.12.2
Forge: 14.23.3.2682
Mekanism: 1.12.2-9.4.10.345
CraftTweaker: 4.1.8
ModTweaker: 4.0.12
ContentTweaker: 1.12.2-4.5.0
Base: 3.7.1

**Comment by Lorexe** [comment]
Hello
Sorry answering now, I was really busy...

So I made a big update of the mod today and include a fix for the renaming of gas :)
You can also create gas without a fluid.

For the problem of coloration with a fluid from contenttweaker, the gas will appear white into JEI, it's a compatibilty problem between contenttweaker/JEI/Mekanism/My mod and it will never be resolve :/ 

Better define your own texture for the fluid, take a look at the [new documentation](https://minecraft.curseforge.com/projects/mekatweaker/pages/gas) :)
