### ISSUE TITLE
No color in JEI Gas Preview

### ISSUE THREAD

**Issue by pupnewfster** [Lorexe/MekaTweaker#2]
If I create a custom liquid in ContentTweaker and then create a gas of that liquid the JEI previews of it is uncolored. This is not the end of the world as in both the machines and the pressurized tubes the gas is colored. However it would be nice to have it fixed.

https://gyazo.com/b93bd3b8849b7e32fa5adedc0f8efb4b

forge: 14.23.4.2739
content tweaker: 4.6.0
JEI: 4.11.0.206
GasTweaker: 1.0

**Comment by Lorexe** [comment]
Hello
Sorry answering now, I was really busy...

I can't change how JEI render Mekanism Gas (define in Mekanism code) and Mekanism has no idea that contenttweaker add fluid with coloration and take the raw white texture...
The only solution is to define your own texture and not using auto-coloration from contenttweaker.

I also made a big update where you can create gas without a fluid, take a look at the [new documentation](https://minecraft.curseforge.com/projects/mekatweaker/pages/gas) :)
