### ISSUE TITLE
Notice or Warning of name change

### ISSUE THREAD

**Issue by Dragnier** [Lorexe/MekaTweaker#3]
Changing your mod the way you did broke every old script and something that detects the old script calls and prints a notice in chat instead of a random craft tweaker error showing due to broken scripts would be super helpful.

**Comment by Lorexe** [comment]
Yes i know it breaks old scripts but I can't intercept CraftTweaker errors :/ 
I could register placeholder class for old name, people will have a friendly error in the log and don't really see it... At least, here, they understand that something go wrong.
