### ISSUE TITLE
[Suggestion] Add support for the parttypes on contenttweaker's material system.

### ISSUE THREAD

**Issue by LeonGC25** [Lorexe/MekaTweaker#7]
The parttypes define what kind of part it is like this: https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Materials/Parts/PartType/ . It would be amazing if you added "gas" as an option.

**Comment by Lorexe** [comment]
Hello, 
Thanks to Kindlich, it's done :D 

It will be soon available on Curse :)
